### ISSUE TITLE
is this working anymore?

### ISSUE THREAD

**Issue by goffy59** [vint21h/fedora-intel-remapped-nvme-device-support#2]
So I tried this on a fedora 37 VM and when using the build-image.sh it eventually fails, the result directory has files in his but the live folder just has error logs. Id be happy to provide some details but seeing as though this hasnt been updated in awhile i just wanna ask about the status of the project or if it could be updated. Also, do I use a vm or do I use it locally. I had to change the virbr0 interface to a different one that my system was using. anymore, any help would be appreciated thanks.

Or could you please provide me with the .iso? I have spent a couple days trying to do this and using chatgpt and google to help with errors. I have not gotten anywhere yet.

**Comment by vint21h** [comment]
Hello,
I know this project looks abandoned, but because I am not using a laptop with this problem now (because it's almost dead). But if I take it from the shelf and you provide me logs, I think we can try to solve this problem.

**Comment by vint21h** [comment]
Yep, I found a problem in "build-image.sh", that needs time to resolve (almost solved).

**Comment by goffy59** [comment]
Thank you for the reply! :) 

I am not 100% sure which logs you want, but if needed I can try to recompile or delete the image folder and rebuild it. Let me know specifically what logs you want or what steps you'd like me to take. Thank you!!!

`[goffy59@fedora37 live]$ cat livemedia.log 
2023-10-12 08:03:12,782 DEBUG livemedia-creator: Namespace(make_iso=True, make_disk=False, make_fsimage=False, make_appliance=False, make_ami=False, make_tar=False, make_tar_disk=False, make_pxe_live=False, make_ostree_live=False, make_oci=False, make_vagrant=False, iso='/home/goffy59/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel/image/live/result/images/boot.iso', iso_only=False, iso_name='Fedora-', ks=['/home/goffy59/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel/image/live/flat-fedora-live-workstation.ks'], image_only=False, no_virt=False, proxy=None, anaconda_args=None, armplatform=None, location=None, logfile='/home/goffy59/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel/image/live/livemedia.log', lorax_templates=None, tmp='/var/tmp', result_dir='/home/goffy59/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel/image/live/live', domacboot=True, extra_boot_args='', disk_image=None, keep_image=False, fs_image=None, image_name=None, tar_disk_name=None, fs_label='Anaconda', image_size_align=0, image_type=None, qemu_args=[], qcow2=False, compression='xz', compress_args=[], app_name=None, app_template=None, app_file='appliance.xml', ram=2048, vcpus=None, vnc=None, arch=None, kernel_args=None, ovmf_path='/usr/share/edk2/ovmf/', virt_uefi=False, no_kvm=False, with_rng='/dev/random', dracut_conf=None, dracut_args=None, live_rootfs_size=10, live_rootfs_keep_size=False, oci_config=None, oci_runtime=None, vagrant_metadata=None, vagrantfile=None, project='Linux', releasever='', volid=None, squashfs_only=False, timeout=None)
2023-10-12 08:03:12,782 INFO livemedia-creator: livemedia-creator v37.12-1
2023-10-12 08:03:12,784 INFO pylorax: selinux is enabled and in Enforcing mode
2023-10-12 08:03:12,786 ERROR livemedia-creator: kickstart file (/home/goffy59/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel/image/live/flat-fedora-live-workstation.ks) is missing.
2023-10-12 08:03:12,786 ERROR livemedia-creator: The iso /home/goffy59/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel/image/live/result/images/boot.iso is missing.
`

**Comment by goffy59** [comment]
My laptop is a acer predator triton 700 pt715-51 which can be included in that list on the main project page. You cannot change to AHCI without physically modding the bios with an SPI Programmer/clip. I ordered one just in case I can't solve this but I'd really prefer to use this method. Endless OS worked fine I Just really didn't like it and it seemed like more trouble than it was worth to customize how I wanted it. I am currently running the build-image.sh script again for some fresh logs, just tell me which log files you want. If you'd like me to recompile the kernel let me know. Takes a couple hours each time for me. Thanks again for replying, you have given me hope! I have never modded a bios like this before so id like to avoid having to learn that but if need be I will learn it.

**Comment by goffy59** [comment]
Hell, if you really wanted I could give you SSH access to my laptop. Whatever I can do to help you help me. Thanks for the hope lol :)

**Comment by vint21h** [comment]
After some script fixes, I have built an image, but I am not sure it is working. I will re-check it, and if it - yes, share it with you. Tomorrow, cause I am a bit busy.

**Comment by goffy59** [comment]
That would be super amazing thank you! If it works please provide a link or if you need a server to send it to let me know and any updates to the script would be cool to attempt a fedora 38 build cause in about about a year I think 37 runs out of updates but honestly take your time. Thanks very much for your efforts! I'm happy either way so I don't have to use am external drive on this laptop anymore.  

I just realized you are based in Ukraine. Slava Ukraini!

**Comment by vint21h** [comment]
I am not sure if is it working, but - https://drive.google.com/file/d/19uVajAPkUXTU_vHdXt7BwTJ8HUF1fupo/view?usp=drive_link, and if not, I will go further with strange behavior with kickstart file.

**Comment by goffy59** [comment]
Originally I was able to get a similar result. but I was trying to take all those iso's boot.iso/etc. and turn it into a live fedora 37 iso so i could install it. I tried installing this on a VM and it just gets stuck at selecting sources and my boot.iso did the same. Are you able to get the live cd creator to work? The final image/iso  size should be similar to a regular fedora iso I think? (2 gb or 3gb or something)


edit:

from my vm:
I found that the directory path was wrong... boot.iso does exist. now im trying to figure out the KS issue.

[goffy59@fedora37 fedora-custom-kernel]$ sudo -E sh -c 'setenforce 0 && livemedia-creator --make-iso --iso="/home/goffy59/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel/kernel/x86_64/image/result/images/boot.iso" --ks flat-fedora-live-workstation.ks --releasever="${FEDORA_VERSION}" --macboot --resultdir=./live/ --live-rootfs-size 10 --iso-name Fedora-"${FEDORA_VERSION}" && setenforce 1'
2023-10-15 01:06:24,226: livemedia-creator v37.12-1
2023-10-15 01:06:24,227: selinux is enabled and in Permissive mode
2023-10-15 01:06:24,229: kickstart file (/home/goffy59/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel/flat-fedora-live-workstation.ks) is missing.

I'll update after I attempt to solve the KS problem.

update2:

`[goffy59@fedora37 fedora-custom-kernel]$ ls
+ ls --color=auto
flat-fedora-live-workstation.ks  image  kernel  livemedia.log  program.log
++ __vte_prompt_command
+++ HISTTIMEFORMAT=
+++ history 1
+++ sed 's/^ *[0-9]\+ *//'
++ local command=ls
++ command=ls
++ local 'pwd=~'
++ '[' /home/goffy59/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel '!=' /home/goffy59 ']'
++ pwd='~/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel'
++ pwd='~/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel'
++ printf '\033]777;notify;Command completed;%s\033\\\033]777;precmd\033\\\033]0;%s@%s:%s\033\\' ls goffy59 fedora37 '~/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel'
++ __vte_osc7
+++ /usr/libexec/vte-urlencode-cwd
++ printf '\033]7;file://%s%s\033\' fedora37 /home/goffy59/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel
[goffy59@fedora37 fedora-custom-kernel]$ sed -i 's#url --mirrorlist="https://mirrors.fedoraproject.org/mirrorlist?repo=rawhide\&arch=$basearch"#url --mirrorlist="https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-$releasever\&arch=$basearch"#g' flat-fedora-live-workstation.ks
sed -i 's#repo --name="rawhide" --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=rawhide\&arch=$basearch#\# repo --name="rawhide" --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=rawhide\&arch=$basearch#g' flat-fedora-live-workstation.ks
sed -i "/^# repo --name=\"rawhide\" --mirrorlist=https:\/\/mirrors.fedoraproject.org\/mirrorlist?repo=rawhide\&arch=\$basearch/a repo --name='fedora' --mirrorlist=https:\/\/mirrors.fedoraproject.org\/mirrorlist?repo=fedora-\$releasever\&arch=\$basearch" flat-fedora-live-workstation.ks
sed -i "/^repo --name='fedora' --mirrorlist=https:\/\/mirrors.fedoraproject.org\/mirrorlist?repo=fedora-\$releasever\&arch=\$basearch/a repo --name='updates' --mirrorlist=https:\/\/mirrors.fedoraproject.org\/mirrorlist?repo=updates-released-f\$releasever\&arch=\$basearch" flat-fedora-live-workstation.ks
sed -i "/^repo --name='updates' --mirrorlist=https:\/\/mirrors.fedoraproject.org\/mirrorlist?repo=updates-released-f\$releasever\&arch=\$basearch/a repo --name='fedora-custom-kernel' --cost=1 --baseurl=http:\/\/${HOST_IP}:8080/" flat-fedora-live-workstation.ks
sed -i 's#part / --size=7680#part / --fstype="ext4" --size=10240#g' flat-fedora-live-workstation.ks
+ sed -i 's#url --mirrorlist="https://mirrors.fedoraproject.org/mirrorlist?repo=rawhide\&arch=$basearch"#url --mirrorlist="https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-$releasever\&arch=$basearch"#g' flat-fedora-live-workstation.ks
+ sed -i 's#repo --name="rawhide" --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=rawhide\&arch=$basearch#\# repo --name="rawhide" --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=rawhide\&arch=$basearch#g' flat-fedora-live-workstation.ks
+ sed -i '/^# repo --name="rawhide" --mirrorlist=https:\/\/mirrors.fedoraproject.org\/mirrorlist?repo=rawhide\&arch=$basearch/a repo --name='\''fedora'\'' --mirrorlist=https:\/\/mirrors.fedoraproject.org\/mirrorlist?repo=fedora-$releasever\&arch=$basearch' flat-fedora-live-workstation.ks
+ sed -i '/^repo --name='\''fedora'\'' --mirrorlist=https:\/\/mirrors.fedoraproject.org\/mirrorlist?repo=fedora-$releasever\&arch=$basearch/a repo --name='\''updates'\'' --mirrorlist=https:\/\/mirrors.fedoraproject.org\/mirrorlist?repo=updates-released-f$releasever\&arch=$basearch' flat-fedora-live-workstation.ks
+ sed -i '/^repo --name='\''updates'\'' --mirrorlist=https:\/\/mirrors.fedoraproject.org\/mirrorlist?repo=updates-released-f$releasever\&arch=$basearch/a repo --name='\''fedora-custom-kernel'\'' --cost=1 --baseurl=http:\/\/192.168.124.20:8080/' flat-fedora-live-workstation.ks
+ sed -i 's#part / --size=7680#part / --fstype="ext4" --size=10240#g' flat-fedora-live-workstation.ks
++ __vte_prompt_command
+++ HISTTIMEFORMAT=
+++ history 1
+++ sed 's/^ *[0-9]\+ *//'
++ local 'command=sed -i '\''s#part / --size=7680#part / --fstype="ext4" --size=10240#g'\'' flat-fedora-live-workstation.ks'
++ command='sed -i '\''s#part / --size=7680#part / --fstype="ext4" --size=10240#g'\'' flat-fedora-live-workstation.ks'
++ local 'pwd=~'
++ '[' /home/goffy59/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel '!=' /home/goffy59 ']'
++ pwd='~/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel'
++ pwd='~/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel'
++ printf '\033]777;notify;Command completed;%s\033\\\033]777;precmd\033\\\033]0;%s@%s:%s\033\\' 'sed -i '\''s#part / --size=7680#part / --fstype="ext4" --size=10240#g'\'' flat-fedora-live-workstation.ks' goffy59 fedora37 '~/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel'
++ __vte_osc7
+++ /usr/libexec/vte-urlencode-cwd
++ printf '\033]7;file://%s%s\033\' fedora37 /home/goffy59/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel
[goffy59@fedora37 fedora-custom-kernel]$ sudo -E sh -c 'setenforce 0 && livemedia-creator --make-iso --iso="/home/goffy59/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel/kernel/x86_64/image/result/images/boot.iso" --ks flat-fedora-live-workstation.ks --releasever="${FEDORA_VERSION}" --macboot --resultdir=./live/ --live-rootfs-size 10 --iso-name Fedora-"${FEDORA_VERSION}" && setenforce 1'
+ sudo -E sh -c 'setenforce 0 && livemedia-creator --make-iso --iso="/home/goffy59/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel/kernel/x86_64/image/result/images/boot.iso" --ks flat-fedora-live-workstation.ks --releasever="${FEDORA_VERSION}" --macboot --resultdir=./live/ --live-rootfs-size 10 --iso-name Fedora-"${FEDORA_VERSION}" && setenforce 1'
2023-10-15 01:10:10,992: livemedia-creator v37.12-1
2023-10-15 01:10:10,993: selinux is enabled and in Permissive mode
/usr/lib/python3.11/site-packages/pykickstart/commands/partition.py:448: KickstartParseWarning: A partition with the mountpoint / has already been defined.
  warnings.warn(_("A partition with the mountpoint %s has already been defined.") % pd.mountpoint, KickstartParseWarning)
2023-10-15 01:10:11,079: disk_img = /home/goffy59/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel/live/lmc-disk-72har5ao.img
2023-10-15 01:10:11,079: Using disk size of 10242MiB
2023-10-15 01:10:11,080: install_log = /home/goffy59/fedora-intel-remapped-nvme-device-support/fedora-custom-kernel/virt-install.log
2023-10-15 01:10:14,400: qemu vnc=127.0.0.1:0
2023-10-15 01:10:14,400: Running qemu
2023-10-15 01:10:14,790: Processing logs from ('127.0.0.1', 43974)

`
waiting for the live iso to be created from the boot.iso/etc.

**Comment by goffy59** [comment]
Its just doing this when I check the virt-install log

usbfs: No such device
08:50:38,255 ERR brltty:file system mount error: usbfs[brltty-usbfs] -> /run/brltty/usbfs: No such device
08:50:38,258 ERR brltty:file system mount error: usbfs[brltty-usbfs] -> /run/brltty/usbfs: No such device
08:50:38,261 ERR brltty:file system mount error: usbfs[brltty-usbfs] -> /run/brltty/usbfs: No such device
08:50:38,264 ERR brltty:file system mount error: usbfs[brltty-usbfs] -> /run/brltty/usbfs: No such device
08:50:38,267 ERR brltty:file system mount error: usbfs[brltty-usbfs] -> /run/brltty/usbfs: No such device
08:50:38,270 ERR brltty:file system mount error: usbfs[brltty-usbfs] -> /run/brltty/usbfs: No such device

i can give you more of the log if needed.. just not sure what you'd want to see to help you better.

edit2:

I stopped it because it looks like it wasn't doing anything. I'll wait for a response and google stuff in the meantime.

**Comment by goffy59** [comment]
OK so basically I am having problems making the live fedora 37 installation iso based on the custom kernel. I think at this point its just an issue with KS and the command used to make the livecd from the custom kernel. I have been trying CHATGPT and google to help figure some of this out and its instructions are different than the ones you used which confuses me. Anyhow, if you have an idea of how to fix the livecd step im all ears. I am definitely outside my comfort zone on linux when it comes to this. I have never attempted this before. But I feel like once I am successful at least once I could then build a fedora 38 workstation. But id prefer to get this working first.

Currently I am working off of the laptop that needs this patch via an external usb drive. So I have to do some of this in a VM to make it easier. If I try to test the live cd I will need to reboot and remove the external drive which has the OS I am working off of and see if it sees the drive to install fedora 37 workstation.

**Comment by vint21h** [comment]
So, if it is still actual, working image - https://drive.google.com/file/d/1PabHlN25jUGWW4HEtfYBBkkPJMqZImie/view?usp=sharing
I will fix the code later.

**Comment by goffy59** [comment]
I tried it out and it appears to freeze and only shows "_", USB drive shows activity before this happens then it stops.

**Comment by goffy59** [comment]
Just a heads up. Im still willing to test this if you like but I got my bios modded and now the advanced menu is unlocked.. it was quite the ordeal. But its completely unlocked and I can use AHCI. If you are curious or need a good contact for a bios modder let me know ill be happy to pass his info your way. Thank you for all your efforts! Let me know if you want me to test my laptop again... I can put it in raid mode and do the test.

**Comment by vint21h** [comment]
![hes_dead_jim_5](https://github.com/vint21h/fedora-intel-remapped-nvme-device-support/assets/895137/ef054c1d-74a3-47e3-bdaa-7df01e9f2a02)
Unfortunately, this kernel patch set is no longer supported and applicable to modern Linux kernel versions.
So, yeah, this is not working anymore.
